export const SHORTEN_URL_SUCCESS = 'SHORTEN_URL_SUCCESS';
export const SHORTEN_LOADING = 'SHORTEN_LOADING';
export const SHORTEN_ERROR = 'SHORTEN_ERROR';
export const FETCH_URLS_SUCCESS = 'FETCH_URLS_SUCCESS';
export const DELETE_URL_SUCCESS = 'DELETE_URL_SUCCESS';
